import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import "./globals.css";
import Leftside from "@/components/custom/Leftside";
import RightSide from "@/components/custom/RightSide";
import Navbar from "@/components/custom/Navbar";
import { StoreInitializer } from "@/components/custom/StoreInitializer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "One Music",
  description: "Generated by create next app",
};

import { Toaster } from "@/components/ui/sonner";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" className="dark">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <StoreInitializer />
          <div className="flex h-screen overflow-hidden">
            <Leftside />
            <div className="flex-1 flex flex-col overflow-hidden">
              <Navbar />
              <main className="flex-1 overflow-y-auto no-scrollbar">
                {children}
              </main>
            </div>
            <RightSide />
          </div>
          <Toaster />
        </body>
      </html>
    </ClerkProvider>
  );
}
